# Generated by Django 6.0.3 on 2026-04-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_meeting_memberprofile_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
