# Generated by Django 6.0.3 on 2026-04-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_meeting_location_meeting_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="rsvp",
            field=models.BooleanField(default=False),
        ),
    ]
